table _measures
	lineageTag: 7130f9b1-7013-4e89-9070-c4a003fe3e38

	measure 'Property Count' =
			
			COUNT(
			    housing_fact[zpid]
			)
		formatString: #,0
		lineageTag: bfac5f31-17a3-40e6-8819-027d1ed826df

	measure 'Average House Price' =
			
			AVERAGE(
			    housing_fact[latestPrice]
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 418ad1c6-b928-489b-b35c-d0394a079ea0

	measure 'Median Home Price' =
			
			MEDIAN(
			    housing_fact[latestPrice]
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2dd48519-f7a9-433e-acd7-6e33cfa6d46b

	measure 'Property Colour 1' =
			
			SWITCH(
			    TRUE(),
			    [Average House Price] >= [Min Parameter Value] &&
			    [Average House Price] <= [Max Parameter Value],
			    "#E0144C",
			    "#CCCCCC"
			)
		lineageTag: e40eda26-c296-4e2a-8c64-1b0c566b0bf0

	measure 'Word Count' =
			
			COUNT(
			    'description'[zpid]
			)
		formatString: #,0
		lineageTag: 8a8d1c8e-0e5f-4be9-9384-23e3011b8180

	measure 'Word Rank' =
			
			RANKX(
			    ALLSELECTED(
			        'Word Summary_pqe'[Value]
			    ),
			    [Word Count],,
			    DESC,
			    Dense
			)
		formatString: 0
		lineageTag: 7102052c-71fa-4277-ae32-ed5c8dd5091d

	measure 'Word Find' = ```
			
			CALCULATE(
			    MIN(
			        'Word Summary_pqe'[Value]
			    ),
			    FILTER(
			        'Word Summary_pqe',
			        [Word Rank] = 
			            SELECTEDVALUE(
			                z_word_rank[Rank]
			            )
			    )
			)
			```
		lineageTag: 8b0c8c97-bb88-42a4-935f-cffb401700d0

	measure 'School Chart Title' =
			
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE(
			        'Parameter (School Groups)'[Parameter (School Groups) Order]
			    ) = 0, "% of Properties by School Rating",
			    SELECTEDVALUE(
			        'Parameter (School Groups)'[Parameter (School Groups) Order]
			    ) = 1, "% of Properties by School Size",
			    SELECTEDVALUE(
			        'Parameter (School Groups)'[Parameter (School Groups) Order]
			    ) = 2, "% of Properties by Avg Students per Teacher",
			    ""
			)
		lineageTag: 08f65554-6430-4585-bec9-5dcac74dca37

	column Column1
		dataType: string
		isHidden
		lineageTag: 765310fb-6de1-4a77-bb09-06b81c15720f
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

