table description
	lineageTag: 55af0ed5-bafd-4571-b910-62daba85cd27

	column zpid
		dataType: int64
		formatString: 0
		lineageTag: 41aa776f-35d8-4949-ad1c-d5db8fffd1b2
		summarizeBy: none
		sourceColumn: zpid

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: c7c91158-12c3-431d-89eb-d909a9c9a76d
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition description = m
		mode: import
		source =
				let
				    Source = austinHousingData_clean,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"zpid", "description"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Other Columns", "description", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"description.1", "description.2", "description.3", "description.4", "description.5", "description.6", "description.7", "description.8", "description.9", "description.10", "description.11", "description.12", "description.13", "description.14", "description.15", "description.16", "description.17", "description.18", "description.19", "description.20", "description.21", "description.22", "description.23", "description.24", "description.25", "description.26", "description.27", "description.28", "description.29", "description.30", "description.31", "description.32", "description.33", "description.34", "description.35", "description.36", "description.37", "description.38", "description.39", "description.40", "description.41", "description.42", "description.43", "description.44", "description.45", "description.46", "description.47", "description.48", "description.49", "description.50", "description.51", "description.52", "description.53", "description.54", "description.55", "description.56", "description.57", "description.58", "description.59", "description.60", "description.61", "description.62", "description.63", "description.64", "description.65", "description.66", "description.67", "description.68", "description.69", "description.70", "description.71", "description.72", "description.73", "description.74", "description.75", "description.76", "description.77", "description.78", "description.79", "description.80", "description.81", "description.82", "description.83", "description.84", "description.85", "description.86", "description.87", "description.88", "description.89", "description.90", "description.91", "description.92", "description.93", "description.94", "description.95", "description.96", "description.97", "description.98", "description.99", "description.100", "description.101", "description.102", "description.103", "description.104", "description.105", "description.106", "description.107", "description.108", "description.109", "description.110", "description.111", "description.112", "description.113", "description.114", "description.115", "description.116", "description.117", "description.118", "description.119", "description.120", "description.121", "description.122", "description.123", "description.124", "description.125", "description.126", "description.127", "description.128", "description.129", "description.130", "description.131", "description.132", "description.133", "description.134", "description.135", "description.136", "description.137", "description.138", "description.139", "description.140", "description.141", "description.142", "description.143", "description.144", "description.145", "description.146", "description.147", "description.148", "description.149", "description.150", "description.151", "description.152", "description.153", "description.154", "description.155", "description.156", "description.157", "description.158", "description.159", "description.160", "description.161", "description.162", "description.163", "description.164", "description.165", "description.166", "description.167", "description.168", "description.169", "description.170", "description.171", "description.172", "description.173", "description.174", "description.175", "description.176", "description.177", "description.178", "description.179", "description.180", "description.181", "description.182", "description.183", "description.184", "description.185", "description.186", "description.187", "description.188", "description.189", "description.190", "description.191", "description.192", "description.193", "description.194", "description.195", "description.196", "description.197", "description.198", "description.199", "description.200", "description.201", "description.202", "description.203", "description.204", "description.205", "description.206", "description.207", "description.208", "description.209", "description.210", "description.211", "description.212", "description.213", "description.214", "description.215", "description.216", "description.217", "description.218", "description.219", "description.220", "description.221", "description.222", "description.223", "description.224", "description.225", "description.226", "description.227", "description.228", "description.229", "description.230", "description.231", "description.232", "description.233", "description.234", "description.235", "description.236", "description.237", "description.238", "description.239", "description.240", "description.241", "description.242", "description.243", "description.244", "description.245", "description.246", "description.247", "description.248", "description.249", "description.250", "description.251", "description.252", "description.253", "description.254", "description.255", "description.256", "description.257", "description.258", "description.259", "description.260", "description.261", "description.262", "description.263", "description.264", "description.265", "description.266", "description.267", "description.268", "description.269", "description.270", "description.271", "description.272", "description.273", "description.274", "description.275", "description.276", "description.277", "description.278", "description.279", "description.280", "description.281", "description.282", "description.283", "description.284", "description.285", "description.286", "description.287", "description.288", "description.289", "description.290", "description.291", "description.292", "description.293", "description.294", "description.295", "description.296", "description.297", "description.298", "description.299", "description.300", "description.301", "description.302", "description.303", "description.304", "description.305", "description.306", "description.307", "description.308", "description.309", "description.310", "description.311", "description.312", "description.313", "description.314", "description.315", "description.316", "description.317", "description.318", "description.319", "description.320", "description.321", "description.322", "description.323", "description.324", "description.325", "description.326", "description.327", "description.328", "description.329", "description.330", "description.331", "description.332", "description.333", "description.334", "description.335", "description.336", "description.337", "description.338", "description.339", "description.340", "description.341", "description.342", "description.343", "description.344", "description.345", "description.346", "description.347", "description.348", "description.349", "description.350", "description.351", "description.352", "description.353", "description.354", "description.355", "description.356", "description.357", "description.358", "description.359", "description.360", "description.361", "description.362", "description.363", "description.364", "description.365", "description.366", "description.367", "description.368", "description.369", "description.370", "description.371", "description.372", "description.373", "description.374", "description.375", "description.376", "description.377", "description.378", "description.379", "description.380", "description.381", "description.382", "description.383", "description.384", "description.385", "description.386", "description.387", "description.388", "description.389", "description.390", "description.391", "description.392", "description.393", "description.394", "description.395", "description.396", "description.397", "description.398", "description.399", "description.400", "description.401", "description.402", "description.403", "description.404", "description.405", "description.406", "description.407", "description.408", "description.409", "description.410", "description.411", "description.412", "description.413", "description.414", "description.415", "description.416", "description.417", "description.418", "description.419", "description.420", "description.421", "description.422", "description.423", "description.424", "description.425", "description.426", "description.427", "description.428", "description.429", "description.430", "description.431", "description.432", "description.433", "description.434", "description.435", "description.436", "description.437", "description.438", "description.439", "description.440", "description.441", "description.442", "description.443", "description.444", "description.445", "description.446", "description.447", "description.448", "description.449", "description.450", "description.451", "description.452", "description.453", "description.454", "description.455", "description.456", "description.457", "description.458", "description.459", "description.460", "description.461", "description.462", "description.463", "description.464", "description.465", "description.466", "description.467", "description.468", "description.469", "description.470", "description.471", "description.472", "description.473", "description.474", "description.475", "description.476", "description.477", "description.478", "description.479", "description.480", "description.481", "description.482", "description.483", "description.484", "description.485", "description.486", "description.487", "description.488", "description.489", "description.490", "description.491", "description.492", "description.493", "description.494", "description.495", "description.496", "description.497", "description.498", "description.499", "description.500", "description.501", "description.502", "description.503", "description.504", "description.505", "description.506", "description.507", "description.508", "description.509", "description.510", "description.511", "description.512", "description.513", "description.514", "description.515", "description.516", "description.517", "description.518", "description.519", "description.520", "description.521", "description.522", "description.523", "description.524", "description.525", "description.526", "description.527", "description.528"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"description.1", type text}, {"description.2", type text}, {"description.3", type text}, {"description.4", type text}, {"description.5", type text}, {"description.6", type text}, {"description.7", type text}, {"description.8", type text}, {"description.9", type text}, {"description.10", type text}, {"description.11", type text}, {"description.12", type text}, {"description.13", type text}, {"description.14", type text}, {"description.15", type text}, {"description.16", type text}, {"description.17", type text}, {"description.18", type text}, {"description.19", type text}, {"description.20", type text}, {"description.21", type text}, {"description.22", type text}, {"description.23", type text}, {"description.24", type text}, {"description.25", type text}, {"description.26", type text}, {"description.27", type text}, {"description.28", type text}, {"description.29", type text}, {"description.30", type text}, {"description.31", type text}, {"description.32", type text}, {"description.33", type text}, {"description.34", type text}, {"description.35", type text}, {"description.36", type text}, {"description.37", type text}, {"description.38", type text}, {"description.39", type text}, {"description.40", type text}, {"description.41", type text}, {"description.42", type text}, {"description.43", type text}, {"description.44", type text}, {"description.45", type text}, {"description.46", type text}, {"description.47", type text}, {"description.48", type text}, {"description.49", type text}, {"description.50", type text}, {"description.51", type text}, {"description.52", type text}, {"description.53", type text}, {"description.54", type text}, {"description.55", type text}, {"description.56", type text}, {"description.57", type text}, {"description.58", type text}, {"description.59", type text}, {"description.60", type text}, {"description.61", type text}, {"description.62", type text}, {"description.63", type text}, {"description.64", type text}, {"description.65", type text}, {"description.66", type text}, {"description.67", type text}, {"description.68", type text}, {"description.69", type text}, {"description.70", type text}, {"description.71", type text}, {"description.72", type text}, {"description.73", type text}, {"description.74", type text}, {"description.75", type text}, {"description.76", type text}, {"description.77", type text}, {"description.78", type text}, {"description.79", type text}, {"description.80", type text}, {"description.81", type text}, {"description.82", type text}, {"description.83", type text}, {"description.84", type text}, {"description.85", type text}, {"description.86", type text}, {"description.87", type text}, {"description.88", type text}, {"description.89", type text}, {"description.90", type text}, {"description.91", type text}, {"description.92", type text}, {"description.93", type text}, {"description.94", type text}, {"description.95", type text}, {"description.96", type text}, {"description.97", type text}, {"description.98", type text}, {"description.99", type text}, {"description.100", type text}, {"description.101", type text}, {"description.102", type text}, {"description.103", type text}, {"description.104", type text}, {"description.105", type text}, {"description.106", type text}, {"description.107", type text}, {"description.108", type text}, {"description.109", type text}, {"description.110", type text}, {"description.111", type text}, {"description.112", type text}, {"description.113", type text}, {"description.114", type text}, {"description.115", type text}, {"description.116", type text}, {"description.117", type text}, {"description.118", type text}, {"description.119", type text}, {"description.120", type text}, {"description.121", type text}, {"description.122", type text}, {"description.123", type text}, {"description.124", type text}, {"description.125", type text}, {"description.126", type text}, {"description.127", type text}, {"description.128", type text}, {"description.129", type text}, {"description.130", type text}, {"description.131", type text}, {"description.132", type text}, {"description.133", type text}, {"description.134", type text}, {"description.135", type text}, {"description.136", type text}, {"description.137", type text}, {"description.138", type text}, {"description.139", type text}, {"description.140", type text}, {"description.141", type text}, {"description.142", type text}, {"description.143", type text}, {"description.144", type text}, {"description.145", type text}, {"description.146", type text}, {"description.147", type text}, {"description.148", type text}, {"description.149", type text}, {"description.150", type text}, {"description.151", type text}, {"description.152", type text}, {"description.153", type text}, {"description.154", type text}, {"description.155", type text}, {"description.156", type text}, {"description.157", type text}, {"description.158", type text}, {"description.159", type text}, {"description.160", type text}, {"description.161", type text}, {"description.162", type text}, {"description.163", type text}, {"description.164", type text}, {"description.165", type text}, {"description.166", type text}, {"description.167", type text}, {"description.168", type text}, {"description.169", type text}, {"description.170", type text}, {"description.171", type text}, {"description.172", type text}, {"description.173", type text}, {"description.174", type text}, {"description.175", type text}, {"description.176", type text}, {"description.177", type text}, {"description.178", type text}, {"description.179", type text}, {"description.180", type text}, {"description.181", type text}, {"description.182", type text}, {"description.183", type text}, {"description.184", type text}, {"description.185", type text}, {"description.186", type text}, {"description.187", type text}, {"description.188", type text}, {"description.189", type text}, {"description.190", type text}, {"description.191", type text}, {"description.192", type text}, {"description.193", type text}, {"description.194", type text}, {"description.195", type text}, {"description.196", type text}, {"description.197", type text}, {"description.198", type text}, {"description.199", type text}, {"description.200", type text}, {"description.201", type text}, {"description.202", type text}, {"description.203", type text}, {"description.204", type text}, {"description.205", type text}, {"description.206", type text}, {"description.207", type text}, {"description.208", type text}, {"description.209", type text}, {"description.210", type text}, {"description.211", type text}, {"description.212", type text}, {"description.213", type text}, {"description.214", type text}, {"description.215", type text}, {"description.216", type text}, {"description.217", type text}, {"description.218", type text}, {"description.219", type text}, {"description.220", type text}, {"description.221", type text}, {"description.222", type text}, {"description.223", type text}, {"description.224", type text}, {"description.225", type text}, {"description.226", type text}, {"description.227", type text}, {"description.228", type text}, {"description.229", type text}, {"description.230", type text}, {"description.231", type text}, {"description.232", type text}, {"description.233", type text}, {"description.234", type text}, {"description.235", type text}, {"description.236", type text}, {"description.237", type text}, {"description.238", type text}, {"description.239", type text}, {"description.240", type text}, {"description.241", type text}, {"description.242", type text}, {"description.243", type text}, {"description.244", type text}, {"description.245", type text}, {"description.246", type text}, {"description.247", type text}, {"description.248", type text}, {"description.249", type text}, {"description.250", type text}, {"description.251", type text}, {"description.252", type text}, {"description.253", type text}, {"description.254", type text}, {"description.255", type text}, {"description.256", type text}, {"description.257", type text}, {"description.258", type text}, {"description.259", type text}, {"description.260", type text}, {"description.261", type text}, {"description.262", type text}, {"description.263", type text}, {"description.264", type text}, {"description.265", type text}, {"description.266", type text}, {"description.267", type text}, {"description.268", type text}, {"description.269", type text}, {"description.270", type text}, {"description.271", type text}, {"description.272", type text}, {"description.273", type text}, {"description.274", type text}, {"description.275", type text}, {"description.276", type text}, {"description.277", type text}, {"description.278", type text}, {"description.279", type text}, {"description.280", type text}, {"description.281", type text}, {"description.282", type text}, {"description.283", type text}, {"description.284", type text}, {"description.285", type text}, {"description.286", type text}, {"description.287", type text}, {"description.288", type text}, {"description.289", type text}, {"description.290", type text}, {"description.291", type text}, {"description.292", type text}, {"description.293", type text}, {"description.294", type text}, {"description.295", type text}, {"description.296", type text}, {"description.297", type text}, {"description.298", type text}, {"description.299", type text}, {"description.300", type text}, {"description.301", type text}, {"description.302", type text}, {"description.303", type text}, {"description.304", type text}, {"description.305", type text}, {"description.306", type text}, {"description.307", type text}, {"description.308", type text}, {"description.309", type text}, {"description.310", type text}, {"description.311", type text}, {"description.312", type text}, {"description.313", type text}, {"description.314", type text}, {"description.315", type text}, {"description.316", type text}, {"description.317", type text}, {"description.318", type text}, {"description.319", type text}, {"description.320", type text}, {"description.321", type text}, {"description.322", type text}, {"description.323", type text}, {"description.324", type text}, {"description.325", type text}, {"description.326", type text}, {"description.327", type text}, {"description.328", type text}, {"description.329", type text}, {"description.330", type text}, {"description.331", type text}, {"description.332", type text}, {"description.333", type text}, {"description.334", type text}, {"description.335", type text}, {"description.336", type text}, {"description.337", type text}, {"description.338", type text}, {"description.339", type text}, {"description.340", type text}, {"description.341", type text}, {"description.342", type text}, {"description.343", type text}, {"description.344", type text}, {"description.345", type text}, {"description.346", type text}, {"description.347", type text}, {"description.348", type text}, {"description.349", type text}, {"description.350", type text}, {"description.351", type text}, {"description.352", type text}, {"description.353", type text}, {"description.354", type text}, {"description.355", type text}, {"description.356", type text}, {"description.357", type text}, {"description.358", type text}, {"description.359", type text}, {"description.360", type text}, {"description.361", type text}, {"description.362", type text}, {"description.363", type text}, {"description.364", type text}, {"description.365", type text}, {"description.366", type text}, {"description.367", type text}, {"description.368", type text}, {"description.369", type text}, {"description.370", type text}, {"description.371", type text}, {"description.372", type text}, {"description.373", type text}, {"description.374", type text}, {"description.375", type text}, {"description.376", type text}, {"description.377", type text}, {"description.378", type text}, {"description.379", type text}, {"description.380", type text}, {"description.381", type text}, {"description.382", type text}, {"description.383", type text}, {"description.384", type text}, {"description.385", type text}, {"description.386", type text}, {"description.387", type text}, {"description.388", type text}, {"description.389", type text}, {"description.390", type text}, {"description.391", type text}, {"description.392", type text}, {"description.393", type text}, {"description.394", type text}, {"description.395", type text}, {"description.396", type text}, {"description.397", type text}, {"description.398", type text}, {"description.399", type text}, {"description.400", type text}, {"description.401", type text}, {"description.402", type text}, {"description.403", type text}, {"description.404", type text}, {"description.405", type text}, {"description.406", type text}, {"description.407", type text}, {"description.408", type text}, {"description.409", type text}, {"description.410", type text}, {"description.411", type text}, {"description.412", type text}, {"description.413", type text}, {"description.414", type text}, {"description.415", type text}, {"description.416", type text}, {"description.417", type text}, {"description.418", type text}, {"description.419", type text}, {"description.420", type text}, {"description.421", type text}, {"description.422", type text}, {"description.423", type text}, {"description.424", type text}, {"description.425", type text}, {"description.426", type text}, {"description.427", type text}, {"description.428", type text}, {"description.429", type text}, {"description.430", type text}, {"description.431", type text}, {"description.432", type text}, {"description.433", type text}, {"description.434", type text}, {"description.435", type text}, {"description.436", type text}, {"description.437", type text}, {"description.438", type text}, {"description.439", type text}, {"description.440", type text}, {"description.441", type text}, {"description.442", type text}, {"description.443", type text}, {"description.444", type text}, {"description.445", type text}, {"description.446", type text}, {"description.447", type text}, {"description.448", type text}, {"description.449", type text}, {"description.450", type text}, {"description.451", type text}, {"description.452", type text}, {"description.453", type text}, {"description.454", type text}, {"description.455", type text}, {"description.456", type text}, {"description.457", type text}, {"description.458", type text}, {"description.459", type text}, {"description.460", type text}, {"description.461", type text}, {"description.462", type text}, {"description.463", type text}, {"description.464", type text}, {"description.465", type text}, {"description.466", type text}, {"description.467", type text}, {"description.468", type text}, {"description.469", type text}, {"description.470", type text}, {"description.471", type text}, {"description.472", type text}, {"description.473", type text}, {"description.474", type text}, {"description.475", type text}, {"description.476", type text}, {"description.477", type text}, {"description.478", type text}, {"description.479", type text}, {"description.480", type text}, {"description.481", type text}, {"description.482", type text}, {"description.483", type text}, {"description.484", type text}, {"description.485", type text}, {"description.486", type text}, {"description.487", type text}, {"description.488", type text}, {"description.489", type text}, {"description.490", type text}, {"description.491", type text}, {"description.492", type text}, {"description.493", type text}, {"description.494", type text}, {"description.495", type text}, {"description.496", type text}, {"description.497", type text}, {"description.498", type text}, {"description.499", type text}, {"description.500", type text}, {"description.501", type text}, {"description.502", type text}, {"description.503", type text}, {"description.504", type text}, {"description.505", type text}, {"description.506", type text}, {"description.507", type text}, {"description.508", type text}, {"description.509", type text}, {"description.510", type text}, {"description.511", type text}, {"description.512", type text}, {"description.513", type text}, {"description.514", type text}, {"description.515", type text}, {"description.516", type text}, {"description.517", type text}, {"description.518", type text}, {"description.519", type text}, {"description.520", type text}, {"description.521", type text}, {"description.522", type text}, {"description.523", type text}, {"description.524", type text}, {"description.525", type text}, {"description.526", type text}, {"description.527", type text}, {"description.528", type text}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"zpid"}, "Attribute", "Value"),
				    #"Removed Columns" = Table.RemoveColumns(#"Unpivoted Columns",{"Attribute"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns",",","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",".","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","!","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","&","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","#","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","$","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","%","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","^","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","*","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","(","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9",")","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","[","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","]","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","{","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","}","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","-","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","/","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","?","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17",";","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18",":","",Replacer.ReplaceText,{"Value"}),
				    #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","+","",Replacer.ReplaceText,{"Value"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value20", each ([Value] <> "" and [Value] <> "#(cr)#(lf)")),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Custom", each Value.Is(Value.FromText([Value]), type number)),
				    #"Filtered Rows1" = Table.SelectRows(#"Added Custom", each ([Custom] = false)),
				    #"Removed Columns1" = Table.RemoveColumns(#"Filtered Rows1",{"Custom"}),
				    #"Inserted Text Length" = Table.AddColumn(#"Removed Columns1", "Length", each Text.Length([Value]), Int64.Type),
				    #"Filtered Rows2" = Table.SelectRows(#"Inserted Text Length", each ([Length] <> 1 and [Length] <> 2)),
				    #"Lowercased Text" = Table.TransformColumns(#"Filtered Rows2",{{"Value", Text.Lower, type text}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Lowercased Text",{{"Value", Text.Proper, type text}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Capitalized Each Word",{"Length"}),
				    #"Filtered Rows3" = Table.SelectRows(#"Removed Columns2", each ([Value] <> "#(tab)This" and [Value] <> "#(cr)#(lf)The" and [Value] <> "1550Mo" and [Value] <> "1650Mo" and [Value] <> "1750Mo" and [Value] <> "1800Mo" and [Value] <> "2000Mo" and [Value] <> "2005Built" and [Value] <> "2195Mo" and [Value] <> "2495Mo" and [Value] <> "2695Mo" and [Value] <> "All" and [Value] <> "And" and [Value] <> "Are" and [Value] <> "Been" and [Value] <> "Can" and [Value] <> "Come" and [Value] <> "Day" and [Value] <> "Del" and [Value] <> "Don’T" and [Value] <> "Etc" and [Value] <> "Footage#(tab)Acres#(cr)#(lf)8800#(tab)573#(cr)#(lf)Bedrooms#(tab)Baths#(cr)#(lf)5#(tab)8#(cr)#(lf)This" and [Value] <> "For" and [Value] <> "Has" and [Value] <> "Have" and [Value] <> "Http6004Arnhemisnow4Salecom" and [Value] <> "Into" and [Value] <> "Just" and [Value] <> "Must" and [Value] <> "Not" and [Value] <> "Only" and [Value] <> "Other" and [Value] <> "Tanya@Jorgensonrealestatecom" and [Value] <> "Than" and [Value] <> "That" and [Value] <> "The" and [Value] <> "Their" and [Value] <> "There" and [Value] <> "Things" and [Value] <> "This" and [Value] <> "Three" and [Value] <> "Through" and [Value] <> "Throughout" and [Value] <> "Under" and [Value] <> "Upon" and [Value] <> "Was" and [Value] <> "With" and [Value] <> "Won'T" and [Value] <> "Would" and [Value] <> "You" and [Value] <> "You'Re" and [Value] <> "Your" and [Value] <> "Yourself"))
				in
				    #"Filtered Rows3"

	annotation PBI_ResultType = Table

