table features_pivot
	lineageTag: 1b4d8fc7-a411-4376-b010-a797869e31d4

	column features_key
		dataType: int64
		formatString: 0
		lineageTag: cbbd7b7d-ab5b-4429-be0d-fc3ea1e3a310
		summarizeBy: none
		sourceColumn: features_key

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: be2b379f-698e-4292-bc58-36edff344b10
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: b7c9833b-c55a-4fe5-82e2-5ca9b3cedea6
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition features_pivot = m
		mode: import
		source =
				let
				    Source = features,
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(Source, {"features_key"}, "Attribute", "Value"),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Unpivoted Columns", "Attribute", Splitter.SplitTextByDelimiter("has", QuoteStyle.Csv), {"Attribute.1", "Attribute.2"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Attribute.1", type text}, {"Attribute.2", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Attribute.1"}),
				    #"Added Prefix" = Table.TransformColumns(#"Removed Columns", {{"Attribute.2", each "Has " & _, type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Prefix",{{"Attribute.2", "Attribute"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

