table features
	lineageTag: 9a1d8722-0ba9-47cf-bea9-7b8c524f70a6

	column features_key
		dataType: int64
		formatString: 0
		lineageTag: 9b375037-32ac-4ab7-a83b-f65600678b9d
		summarizeBy: none
		sourceColumn: features_key

		annotation SummarizationSetBy = Automatic

	column hasAssociation
		dataType: string
		lineageTag: 77990c6a-fc7d-4dec-b181-76a5756dfae6
		summarizeBy: none
		sourceColumn: hasAssociation

		annotation SummarizationSetBy = Automatic

	column hasCooling
		dataType: string
		lineageTag: 905141ec-a6a5-4d7f-b8d7-2afc36aa6078
		summarizeBy: none
		sourceColumn: hasCooling

		annotation SummarizationSetBy = Automatic

	column hasGarage
		dataType: string
		lineageTag: fcea82db-2138-44bf-b3c3-43bfbc8f1742
		summarizeBy: none
		sourceColumn: hasGarage

		annotation SummarizationSetBy = Automatic

	column hasHeating
		dataType: string
		lineageTag: 30b64487-3e77-40de-8b3b-ae2775f7e01c
		summarizeBy: none
		sourceColumn: hasHeating

		annotation SummarizationSetBy = Automatic

	column hasSpa
		dataType: string
		lineageTag: 1aaf32a7-702e-49cc-accf-2cb26d4f6d34
		summarizeBy: none
		sourceColumn: hasSpa

		annotation SummarizationSetBy = Automatic

	column hasView
		dataType: string
		lineageTag: 1ba7dba5-43f7-461d-876c-b659ba415d36
		summarizeBy: none
		sourceColumn: hasView

		annotation SummarizationSetBy = Automatic

	partition features = m
		mode: import
		source =
				let
				    Source = austinHousingData_clean,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"hasAssociation", "hasCooling", "hasGarage", "hasHeating", "hasSpa", "hasView"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "features_key"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"features_key", "hasAssociation", "hasCooling", "hasGarage", "hasHeating", "hasSpa", "hasView"})
				in
				    #"Reordered Columns"

	annotation PBI_ResultType = Table

