table house
	lineageTag: 321f969a-b886-4279-82fa-8d9fbb463faf

	column house_key
		dataType: int64
		formatString: 0
		lineageTag: 39bddbe0-307e-4f78-9c1e-147e0f16cb76
		summarizeBy: none
		sourceColumn: house_key

		annotation SummarizationSetBy = Automatic

	column garageSpaces
		dataType: int64
		formatString: 0
		lineageTag: 83b5e206-1b02-4852-99fa-0664b400a26f
		summarizeBy: none
		sourceColumn: garageSpaces

		annotation SummarizationSetBy = Automatic

	column homeType
		dataType: string
		lineageTag: 99cc1663-b95a-462f-a9df-100a2c148cf3
		summarizeBy: none
		sourceColumn: homeType

		annotation SummarizationSetBy = Automatic

	column parkingSpaces
		dataType: int64
		formatString: 0
		lineageTag: 45ba65f8-92f8-4934-ab6f-b59efe0b2c4e
		summarizeBy: none
		sourceColumn: parkingSpaces

		annotation SummarizationSetBy = Automatic

	column numOfAccessibilityFeatures
		dataType: int64
		formatString: 0
		lineageTag: e694e279-bbec-4cc6-ada4-882602ec91f2
		summarizeBy: none
		sourceColumn: numOfAccessibilityFeatures

		annotation SummarizationSetBy = Automatic

	column numOfAppliances
		dataType: int64
		formatString: 0
		lineageTag: 6c13c49c-08b0-439e-b99c-5b6e4ff0853f
		summarizeBy: none
		sourceColumn: numOfAppliances

		annotation SummarizationSetBy = Automatic

	column numOfParkingFeatures
		dataType: int64
		formatString: 0
		lineageTag: dacba76d-0f18-4979-993c-20fe25cf1c73
		summarizeBy: none
		sourceColumn: numOfParkingFeatures

		annotation SummarizationSetBy = Automatic

	column numOfPatioAndPorchFeatures
		dataType: int64
		formatString: 0
		lineageTag: d56cec19-8d26-4c48-8343-3edf6c0183fb
		summarizeBy: none
		sourceColumn: numOfPatioAndPorchFeatures

		annotation SummarizationSetBy = Automatic

	column numOfSecurityFeatures
		dataType: int64
		formatString: 0
		lineageTag: f1279b93-53ea-4bdb-ba9d-95be9e916960
		summarizeBy: none
		sourceColumn: numOfSecurityFeatures

		annotation SummarizationSetBy = Automatic

	column numOfWaterfrontFeatures
		dataType: int64
		formatString: 0
		lineageTag: 3092c190-10b0-483e-b39f-2fed1e4c8e01
		summarizeBy: none
		sourceColumn: numOfWaterfrontFeatures

		annotation SummarizationSetBy = Automatic

	column numOfWindowFeatures
		dataType: int64
		formatString: 0
		lineageTag: 742fc6bc-d1eb-4cc2-844c-bb36de1b594b
		summarizeBy: none
		sourceColumn: numOfWindowFeatures

		annotation SummarizationSetBy = Automatic

	column numOfCommunityFeatures
		dataType: int64
		formatString: 0
		lineageTag: 2e20ac46-e4b1-484a-b990-0b5869abfbe6
		summarizeBy: none
		sourceColumn: numOfCommunityFeatures

		annotation SummarizationSetBy = Automatic

	column numOfBathrooms
		dataType: int64
		formatString: 0
		lineageTag: ae27a3f1-7750-4537-bb4c-8254d5862d39
		summarizeBy: none
		sourceColumn: numOfBathrooms

		annotation SummarizationSetBy = Automatic

	column numOfBedrooms
		dataType: int64
		formatString: 0
		lineageTag: 4353bbe0-dabc-448b-8e3f-fb10cbe01ddf
		summarizeBy: none
		sourceColumn: numOfBedrooms

		annotation SummarizationSetBy = Automatic

	column numOfStories
		dataType: int64
		formatString: 0
		lineageTag: e7e9b77e-461e-4bd5-b17e-cd8e23030363
		summarizeBy: none
		sourceColumn: numOfStories

		annotation SummarizationSetBy = Automatic

	partition house = m
		mode: import
		source =
				let
				    Source = austinHousingData_clean,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"garageSpaces", "homeType", "parkingSpaces", "numOfAccessibilityFeatures", "numOfAppliances", "numOfParkingFeatures", "numOfPatioAndPorchFeatures", "numOfSecurityFeatures", "numOfWaterfrontFeatures", "numOfWindowFeatures", "numOfCommunityFeatures", "numOfBathrooms", "numOfBedrooms", "numOfStories"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "house_key"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"house_key", "garageSpaces", "homeType", "parkingSpaces", "numOfAccessibilityFeatures", "numOfAppliances", "numOfParkingFeatures", "numOfPatioAndPorchFeatures", "numOfSecurityFeatures", "numOfWaterfrontFeatures", "numOfWindowFeatures", "numOfCommunityFeatures", "numOfBathrooms", "numOfBedrooms", "numOfStories"})
				in
				    #"Reordered Columns"

	annotation PBI_ResultType = Exception

