table location
	lineageTag: a3f5cff9-007c-43f1-b404-cfa9f21fd7d2

	column zpid
		dataType: int64
		formatString: 0
		lineageTag: 39f3f12e-a398-426c-b377-67960a6d0a9b
		summarizeBy: none
		sourceColumn: zpid

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 881f07be-9b93-4ab6-a76e-ef532cdec18e
		dataCategory: City
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column streetAddress
		dataType: string
		lineageTag: 9f3d7a98-dc54-4896-bd2a-ca135018e1bd
		dataCategory: Address
		summarizeBy: none
		sourceColumn: streetAddress

		annotation SummarizationSetBy = Automatic

	column zipcode
		dataType: int64
		formatString: 0
		lineageTag: f9a45608-428d-429d-a5a9-0038daa0e97a
		dataCategory: PostalCode
		summarizeBy: sum
		sourceColumn: zipcode

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 00d729e6-784b-44db-bc5a-2cd9a2b2b17c
		dataCategory: Latitude
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: f61b3eba-40cf-4d62-9cac-702f4e213ea4
		dataCategory: Longitude
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition location = m
		mode: import
		source =
				let
				    Source = austinHousingData_clean,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"zpid", "city", "streetAddress", "zipcode", "latitude", "longitude"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

