table 'Parameter (Range)'
	lineageTag: 5789b092-fa14-473c-8d33-84a4f5357f92

	measure 'Min Parameter Value' =
			
			MIN(
			    'Parameter (Range)'[Parameter]
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 032f15bb-b904-40f8-b4ad-140973d1cf68

	measure 'Max Parameter Value' =
			
			MAX(
			    'Parameter (Range)'[Parameter]
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c0d4a15e-ad06-42d2-947e-928884a55e34

	column Parameter
		dataType: int64
		formatString: #,0
		lineageTag: a19a4b80-9f4f-41de-84e8-2cc6e5cd69e3
		summarizeBy: none
		isDataTypeInferred
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Parameter (Range)' = calculated
		mode: import
		source = GENERATESERIES(5500, 13500000, 10000)

	annotation PBI_Id = 615ce7e4369a4da8890fddad87aa7954

