table schools
	lineageTag: c5e269e1-1c90-4793-9535-68457e97245c

	column school_key
		dataType: int64
		formatString: 0
		lineageTag: 2cfb6c52-284a-46e3-8d29-f1cc88c56166
		summarizeBy: none
		sourceColumn: school_key

		annotation SummarizationSetBy = Automatic

	column numOfPrimarySchools
		dataType: int64
		formatString: 0
		lineageTag: 278429ed-7914-4724-ba00-10ab73aec840
		summarizeBy: none
		sourceColumn: numOfPrimarySchools

		annotation SummarizationSetBy = Automatic

	column numOfElementarySchools
		dataType: int64
		formatString: 0
		lineageTag: 61f0da00-9aa9-418e-8366-7dbccaab7053
		summarizeBy: none
		sourceColumn: numOfElementarySchools

		annotation SummarizationSetBy = Automatic

	column numOfMiddleSchools
		dataType: int64
		formatString: 0
		lineageTag: 61d6035f-d251-4d9c-9a3c-105319897539
		summarizeBy: none
		sourceColumn: numOfMiddleSchools

		annotation SummarizationSetBy = Automatic

	column numOfHighSchools
		dataType: int64
		formatString: 0
		lineageTag: 2677b723-9976-43f4-9380-d7f5a85ec23d
		summarizeBy: none
		sourceColumn: numOfHighSchools

		annotation SummarizationSetBy = Automatic

	column averageSchoolDistance
		dataType: double
		lineageTag: 1e2dba5f-1005-4577-bb57-6f045f564f1c
		summarizeBy: none
		sourceColumn: averageSchoolDistance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avgSchoolRating
		dataType: double
		lineageTag: 3623eb33-3792-40f4-aa91-ece25d4f15ad
		summarizeBy: none
		sourceColumn: avgSchoolRating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"schools","TableItemName":"Group (Rating)","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"schools","TableItemName":"Group Rating Order","ObjectType":4},"LinkType":"UsedInGroup"}]

	column avgSchoolSize
		dataType: int64
		formatString: #,0
		lineageTag: c3d43e41-45eb-4ea1-bf22-ca665be2297d
		summarizeBy: none
		sourceColumn: avgSchoolSize

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"schools","TableItemName":"Group (Size)","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"schools","TableItemName":"Group School Size Order","ObjectType":4},"LinkType":"UsedInGroup"}]

	column MedianStudentsPerTeacher
		dataType: int64
		formatString: 0
		lineageTag: 98428d40-dc1e-4a98-8fa5-35b0bf089959
		summarizeBy: none
		sourceColumn: MedianStudentsPerTeacher

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"schools","TableItemName":"Group (SPT)","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"schools","TableItemName":"Group SPT Order","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Group (Rating)' =
			SWITCH(
				TRUE,
				ISBLANK('schools'[avgSchoolRating]),
				"(Blank)",
				'schools'[avgSchoolRating] IN {5,
					5.3,
					5.7,
					5.8,
					6,
					6.3,
					6.5,
					6.7},
				"Average",
				'schools'[avgSchoolRating] IN {9,
					9.3,
					9.5},
				"Exceptional",
				'schools'[avgSchoolRating] IN {7,
					7.3,
					7.7,
					8,
					8.3,
					8.5,
					8.7},
				"Good",
				'schools'[avgSchoolRating] IN {2.3,
					2.7,
					3,
					3.3,
					3.5,
					3.7,
					4,
					4.3,
					4.7},
				"Poor",
				"Other"
			)
		lineageTag: c162c45b-5af4-4b3a-964b-14b269091382
		summarizeBy: none
		sortByColumn: 'Group Rating Order'

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "schools"
				          }
				        },
				        "Property": "avgSchoolRating"
				      }
				    }
				  ]
				}

		changedProperty = SortByColumn

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"s","Entity":"schools"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolRating"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"Average","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolRating"}}],"Values":[[{"Literal":{"Value":"5D"}}],[{"Literal":{"Value":"5.3D"}}],[{"Literal":{"Value":"5.7D"}}],[{"Literal":{"Value":"5.8D"}}],[{"Literal":{"Value":"6D"}}],[{"Literal":{"Value":"6.3D"}}],[{"Literal":{"Value":"6.5D"}}],[{"Literal":{"Value":"6.7D"}}]]}}},{"DisplayName":"Exceptional","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolRating"}}],"Values":[[{"Literal":{"Value":"9D"}}],[{"Literal":{"Value":"9.3D"}}],[{"Literal":{"Value":"9.5D"}}]]}}},{"DisplayName":"Good","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolRating"}}],"Values":[[{"Literal":{"Value":"7D"}}],[{"Literal":{"Value":"7.3D"}}],[{"Literal":{"Value":"7.7D"}}],[{"Literal":{"Value":"8D"}}],[{"Literal":{"Value":"8.3D"}}],[{"Literal":{"Value":"8.5D"}}],[{"Literal":{"Value":"8.7D"}}]]}}},{"DisplayName":"Poor","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolRating"}}],"Values":[[{"Literal":{"Value":"2.3D"}}],[{"Literal":{"Value":"2.7D"}}],[{"Literal":{"Value":"3D"}}],[{"Literal":{"Value":"3.3D"}}],[{"Literal":{"Value":"3.5D"}}],[{"Literal":{"Value":"3.7D"}}],[{"Literal":{"Value":"4D"}}],[{"Literal":{"Value":"4.3D"}}],[{"Literal":{"Value":"4.7D"}}]]}}},{"DisplayName":"Other"}]}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Group (Size)' =
			SWITCH(
				TRUE,
				ISBLANK('schools'[avgSchoolSize]),
				"(Blank)",
				'schools'[avgSchoolSize] IN {1300,
					1400,
					1500},
				"Large",
				'schools'[avgSchoolSize] IN {1000,
					1100,
					1200},
				"Medium",
				'schools'[avgSchoolSize] IN {700,
					800,
					900},
				"Smalll",
				'schools'[avgSchoolSize] IN {1600,
					1700,
					1800,
					1900},
				"Very Large",
				'schools'[avgSchoolSize] IN {400,
					500,
					600},
				"Very Small",
				"Other"
			)
		formatString: #,0
		lineageTag: 8227a520-2b89-4dcd-a5fc-8a4ec9fa22ff
		summarizeBy: none
		sortByColumn: 'Group School Size Order'

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "schools"
				          }
				        },
				        "Property": "avgSchoolSize"
				      }
				    }
				  ]
				}

		changedProperty = SortByColumn

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"s","Entity":"schools"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolSize"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"Large","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolSize"}}],"Values":[[{"Literal":{"Value":"1300L"}}],[{"Literal":{"Value":"1400L"}}],[{"Literal":{"Value":"1500L"}}]]}}},{"DisplayName":"Medium","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolSize"}}],"Values":[[{"Literal":{"Value":"1000L"}}],[{"Literal":{"Value":"1100L"}}],[{"Literal":{"Value":"1200L"}}]]}}},{"DisplayName":"Smalll","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolSize"}}],"Values":[[{"Literal":{"Value":"700L"}}],[{"Literal":{"Value":"800L"}}],[{"Literal":{"Value":"900L"}}]]}}},{"DisplayName":"Very Large","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolSize"}}],"Values":[[{"Literal":{"Value":"1600L"}}],[{"Literal":{"Value":"1700L"}}],[{"Literal":{"Value":"1800L"}}],[{"Literal":{"Value":"1900L"}}]]}}},{"DisplayName":"Very Small","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolSize"}}],"Values":[[{"Literal":{"Value":"400L"}}],[{"Literal":{"Value":"500L"}}],[{"Literal":{"Value":"600L"}}]]}}},{"DisplayName":"Other"}]}

		annotation SummarizationSetBy = Automatic

	column 'Group (SPT)' =
			SWITCH(
				TRUE,
				ISBLANK('schools'[MedianStudentsPerTeacher]),
				"(Blank)",
				'schools'[MedianStudentsPerTeacher] IN {17,
					18,
					19},
				"Large Class Sizes",
				'schools'[MedianStudentsPerTeacher] IN {14,
					15,
					16},
				"Medium Class Sizes",
				'schools'[MedianStudentsPerTeacher] IN {10,
					11,
					12,
					13},
				"Small Class Sizes",
				"Other"
			)
		lineageTag: e60ac132-9b72-4278-9e49-5c5c868ce815
		summarizeBy: none
		sortByColumn: 'Group SPT Order'

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "schools"
				          }
				        },
				        "Property": "MedianStudentsPerTeacher"
				      }
				    }
				  ]
				}

		changedProperty = SortByColumn

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"s","Entity":"schools"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"MedianStudentsPerTeacher"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"Large Class Sizes","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"MedianStudentsPerTeacher"}}],"Values":[[{"Literal":{"Value":"17L"}}],[{"Literal":{"Value":"18L"}}],[{"Literal":{"Value":"19L"}}]]}}},{"DisplayName":"Medium Class Sizes","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"MedianStudentsPerTeacher"}}],"Values":[[{"Literal":{"Value":"14L"}}],[{"Literal":{"Value":"15L"}}],[{"Literal":{"Value":"16L"}}]]}}},{"DisplayName":"Small Class Sizes","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"MedianStudentsPerTeacher"}}],"Values":[[{"Literal":{"Value":"10L"}}],[{"Literal":{"Value":"11L"}}],[{"Literal":{"Value":"12L"}}],[{"Literal":{"Value":"13L"}}]]}}},{"DisplayName":"Other"}]}

		annotation SummarizationSetBy = Automatic

	column 'Group Rating Order' =
			SWITCH(
				TRUE,
				ISBLANK('schools'[avgSchoolRating]),
				"(Blank)",
				'schools'[avgSchoolRating] IN {2.3,
					2.7,
					3,
					3.3,
					3.5,
					3.7,
					4,
					4.3,
					4.7},
				"1",
				'schools'[avgSchoolRating] IN {5,
					5.3,
					5.7,
					5.8,
					6,
					6.3,
					6.5,
					6.7},
				"2",
				'schools'[avgSchoolRating] IN {7,
					7.3,
					7.7,
					8,
					8.3,
					8.5,
					8.7},
				"3",
				'schools'[avgSchoolRating] IN {9,
					9.3,
					9.5},
				"4",
				"Other"
			)
		lineageTag: 8ecc47b7-7e18-4744-8c7b-85444829788c
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "schools"
				          }
				        },
				        "Property": "avgSchoolRating"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"s","Entity":"schools"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolRating"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"1","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolRating"}}],"Values":[[{"Literal":{"Value":"2.3D"}}],[{"Literal":{"Value":"2.7D"}}],[{"Literal":{"Value":"3D"}}],[{"Literal":{"Value":"3.3D"}}],[{"Literal":{"Value":"3.5D"}}],[{"Literal":{"Value":"3.7D"}}],[{"Literal":{"Value":"4D"}}],[{"Literal":{"Value":"4.3D"}}],[{"Literal":{"Value":"4.7D"}}]]}}},{"DisplayName":"2","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolRating"}}],"Values":[[{"Literal":{"Value":"5D"}}],[{"Literal":{"Value":"5.3D"}}],[{"Literal":{"Value":"5.7D"}}],[{"Literal":{"Value":"5.8D"}}],[{"Literal":{"Value":"6D"}}],[{"Literal":{"Value":"6.3D"}}],[{"Literal":{"Value":"6.5D"}}],[{"Literal":{"Value":"6.7D"}}]]}}},{"DisplayName":"3","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolRating"}}],"Values":[[{"Literal":{"Value":"7D"}}],[{"Literal":{"Value":"7.3D"}}],[{"Literal":{"Value":"7.7D"}}],[{"Literal":{"Value":"8D"}}],[{"Literal":{"Value":"8.3D"}}],[{"Literal":{"Value":"8.5D"}}],[{"Literal":{"Value":"8.7D"}}]]}}},{"DisplayName":"4","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolRating"}}],"Values":[[{"Literal":{"Value":"9D"}}],[{"Literal":{"Value":"9.3D"}}],[{"Literal":{"Value":"9.5D"}}]]}}},{"DisplayName":"Other"}]}

		annotation SummarizationSetBy = Automatic

	column 'Group School Size Order' =
			SWITCH(
				TRUE,
				ISBLANK('schools'[avgSchoolSize]),
				"(Blank)",
				'schools'[avgSchoolSize] IN {400,
					500,
					600},
				"1",
				'schools'[avgSchoolSize] IN {700,
					800,
					900},
				"2",
				'schools'[avgSchoolSize] IN {1000,
					1100,
					1200},
				"3",
				'schools'[avgSchoolSize] IN {1300,
					1400,
					1500},
				"4",
				'schools'[avgSchoolSize] IN {1600,
					1700,
					1800,
					1900},
				"5",
				"Other"
			)
		formatString: #,0
		lineageTag: 32933a5f-13a0-4d45-9110-f6447a326a7d
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "schools"
				          }
				        },
				        "Property": "avgSchoolSize"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"s","Entity":"schools"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolSize"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"1","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolSize"}}],"Values":[[{"Literal":{"Value":"400L"}}],[{"Literal":{"Value":"500L"}}],[{"Literal":{"Value":"600L"}}]]}}},{"DisplayName":"2","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolSize"}}],"Values":[[{"Literal":{"Value":"700L"}}],[{"Literal":{"Value":"800L"}}],[{"Literal":{"Value":"900L"}}]]}}},{"DisplayName":"3","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolSize"}}],"Values":[[{"Literal":{"Value":"1000L"}}],[{"Literal":{"Value":"1100L"}}],[{"Literal":{"Value":"1200L"}}]]}}},{"DisplayName":"4","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolSize"}}],"Values":[[{"Literal":{"Value":"1300L"}}],[{"Literal":{"Value":"1400L"}}],[{"Literal":{"Value":"1500L"}}]]}}},{"DisplayName":"5","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"avgSchoolSize"}}],"Values":[[{"Literal":{"Value":"1600L"}}],[{"Literal":{"Value":"1700L"}}],[{"Literal":{"Value":"1800L"}}],[{"Literal":{"Value":"1900L"}}]]}}},{"DisplayName":"Other"}]}

		annotation SummarizationSetBy = Automatic

	column 'Group SPT Order' =
			SWITCH(
				TRUE,
				ISBLANK('schools'[MedianStudentsPerTeacher]),
				"(Blank)",
				'schools'[MedianStudentsPerTeacher] IN {10,
					11,
					12,
					13},
				"1",
				'schools'[MedianStudentsPerTeacher] IN {14,
					15,
					16},
				"2",
				'schools'[MedianStudentsPerTeacher] IN {17,
					18,
					19},
				"3",
				"Other"
			)
		lineageTag: f77905f3-ccb1-4658-8e90-7e5a5d8755fa
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "schools"
				          }
				        },
				        "Property": "MedianStudentsPerTeacher"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"s","Entity":"schools"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"MedianStudentsPerTeacher"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"1","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"MedianStudentsPerTeacher"}}],"Values":[[{"Literal":{"Value":"10L"}}],[{"Literal":{"Value":"11L"}}],[{"Literal":{"Value":"12L"}}],[{"Literal":{"Value":"13L"}}]]}}},{"DisplayName":"2","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"MedianStudentsPerTeacher"}}],"Values":[[{"Literal":{"Value":"14L"}}],[{"Literal":{"Value":"15L"}}],[{"Literal":{"Value":"16L"}}]]}}},{"DisplayName":"3","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"MedianStudentsPerTeacher"}}],"Values":[[{"Literal":{"Value":"17L"}}],[{"Literal":{"Value":"18L"}}],[{"Literal":{"Value":"19L"}}]]}}},{"DisplayName":"Other"}]}

		annotation SummarizationSetBy = Automatic

	partition schools = m
		mode: import
		source =
				let
				    Source = austinHousingData_clean,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"numOfPrimarySchools", "numOfElementarySchools", "numOfMiddleSchools", "numOfHighSchools", "averageSchoolDistance", "avgSchoolRating", "avgSchoolSize", "MedianStudentsPerTeacher"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "numOfPrimarySchools", "numOfElementarySchools", "numOfMiddleSchools", "numOfHighSchools", "averageSchoolDistance", "avgSchoolRating", "avgSchoolSize", "MedianStudentsPerTeacher"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "school_key"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Exception

